### ISSUE TITLE
pagination 

### ISSUE THREAD

**Issue by murus** [TetraTutorials/clean-android#2]
Dear Sir , 
First of all i would like to thanks your  great tutorial . it is very good . i am murugan from India , i'm android developer 4 +exp . i really enjoyed your tutorial . it is very clear and useful . i have a doubt in pagination page i would like to change pagination by dynamic while scrolling the list view how to do it please help me to achieve this thanks in advance.

**Comment by renegens** [comment]
This is not an issue but a feature request. Right now there is no pagination in the course so we cannot support that. There are although plenty of tutorials on the internet.

**Comment by murus** [comment]
Thanks for your replay message .......
